#!/usr/bin/python
import os, sys
from wallaby import *
import actions as a
    
def main():
    a.first_line_follow()       

if __name__== "__main__":
    sys.stdout = os.fdopen(sys.stdout.fileno(),"w",0)
    main();
