#!/usr/bin/python
import os, sys
from wallaby import *
import actions as a
    
def main():
    print "Hello World"
    a.line_follow_left()       

if __name__== "__main__":
    sys.stdout = os.fdopen(sys.stdout.fileno(),"w",0)
    main();
