#!/usr/bin/python
import os, sys
from wallaby import *
import actions as a
import linefollow as f

def main():
    print "Hello World"
    f.lfollow_right_bstop(30)
    a.check_parking()
        
if __name__== "__main__":
    sys.stdout = os.fdopen(sys.stdout.fileno(),"w",0)
    main();
